services:
  video-downloader-app:
    env_file:
      - next-app/.env
    build:
      context: .
      dockerfile: docker/next.Dockerfile
    ports:
      - "${NEXT_PORT:-3000}:3000"

  fastapi-server:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    ports:
      - "${FAST_PORT:-8000}:${FAST_PORT:-8000}"
    env_file:
      - .env
    environment:
      HOST: ${FAST_HOST:-0.0.0.0}
      PORT: ${FAST_PORT:-8000}
      REDIS_ADDRESS: redis
    volumes:
      - thumbnails:/app/thumbnails
      - videos:/app/videos

  celery-worker:
    build:
      context: .
      dockerfile: docker/celery.Dockerfile  # Adjust if needed
    env_file:
      - .env
    volumes:
      - thumbnails:/app/thumbnails
      - videos:/app/videos

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

volumes:
  thumbnails:
  videos: